name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      # - name: Run Formatting Check
      #   run: black --check .

      - name: Run Linter
        run: ruff check .

      - name: Run Tests
        run: python manage.py test
  pr-comment:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            // TODO: Use github.rest.issues.createComment to post a message.
            // You will need to pass an object with: issue_number, owner, repo, and body.
            // Check out the actions/github-script docs for an exact example!
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "CI checks have completed successfully"
            });